# https://docs.travis-ci.com/user/reference/windows
# https://docs.travis-ci.com/user/languages/python
# https://chocolatey.org/packages/python
# https://www.pyinstaller.org

# install: Installs Python and pip installs Flake8, PyInstaller, requirements.txt
# before_script: Executes run-specific tools and then sets $RUN_WINPWNAGE
# script: Executes WinPwnage

os: windows      # Windows Server, version 1809 -- Platform: Windows-10-10.0.17134-SP0
language: shell  # 'language: python' is not yet supported on Travis CI Windows

env:
  global:
    - PATH=/c/Python39:/c/Python39/Scripts:$PATH

jobs:
  include:
    - name: "Run tests"
    - name: "Build exe with PyInstaller"
      before_script:
        # The next line makes a .exe that fails to write to stdout
        # - pyinstaller --onefile winpwnage.py
        # Workaround: The next three lines inexplicably build a usable .exe
        - cp main.py main_copy.py              # flip
        - pyinstaller --onefile main_copy.py
        - mv dist/main_copy.exe dist/main.exe  # flop
        - sleep 1  # Give PyInstaller a second to finish writing to stdout
        - ls -l dist  # See file size, etc.
        - RUN_WINPWNAGE=dist/main.exe

install:
  - choco install python --version 3.9.1
  - pip3 install flake8 pyinstaller -r requirements.txt

before_script:
  - flake8 . --count --select=E9,F401,F63,F72,F82 --show-source --statistics
  - RUN_WINPWNAGE="python main.py"

script:
  # Scan the function groups
  - $RUN_WINPWNAGE --scan uac
  - $RUN_WINPWNAGE --scan persist
  - $RUN_WINPWNAGE --scan elevate
